# Generated by Django 5.1.2 on 2024-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
