# Generated by Django 6.0.6 on 2026-07-17 06:39

import app.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_notification_users(apps, schema_editor):
    Notification = apps.get_model('app', 'Notification')
    CustomUser = apps.get_model('app', 'CustomUser')

    fallback_user, _ = CustomUser.objects.get_or_create(
        username='system',
        defaults={
            'email': 'system@example.com',
            'is_active': True,
            'is_staff': False,
            'is_superuser': False,
        },
    )

    for notification in Notification.objects.all():
        if notification.actor_id is None:
            notification.actor_id = notification.recipient_id or fallback_user.pk

        if notification.recipient_id is None:
            notification.recipient_id = notification.actor_id or fallback_user.pk

        notification.save(update_fields=['actor', 'recipient'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/', validators=[app.core.validators.validate_image_size])),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/%Y/%m/', validators=[app.core.validators.validate_video_size])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/%Y/%m/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Video duration in seconds.')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Carousel order.')),
            ],
            options={
                'db_table': 'post_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saved_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_sender__893501_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_author__aaae70_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_created_060265_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_media_t_eb72bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_is_publ_a63d0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_views_c_bb6096_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_likes_c_1d1075_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='actor',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('reply', 'Reply'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.RunPython(populate_notification_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=2200),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='saves_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, help_text='Unique hashtag name.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='URL-friendly hashtag.', unique=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_hidden'], name='comments_is_hidd_c63e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_pinned'], name='comments_is_pinn_f5382a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['actor'], name='notificatio_actor_i_e2a3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_author__f2f966_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', '-created_at'], name='posts_visibil_c2b22e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-likes_count'], name='posts_likes_c_a3a26f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views_count'], name='posts_views_c_633d4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='prevent_self_parent'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.post'),
        ),
        migrations.AddField(
            model_name='save',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='app.post'),
        ),
        migrations.AddField(
            model_name='save',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='post_media_post_id_fc20f0_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['media_type'], name='post_media_media_t_f60c3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'order'), name='unique_media_order_per_post'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['user'], name='saved_posts_user_id_fdf308_idx'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['post'], name='saved_posts_post_id_0a01dc_idx'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['created_at'], name='saved_posts_created_8a7d22_idx'),
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_saved_post'),
        ),
    ]
