# Generated by Django 6.0.6 on 2026-07-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_notification_actor_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 10)), name='post_media_order_range'),
        ),
    ]
