from .base import *

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])

DEBUG = env.bool("DJANGO_DEBUG", default=env.bool("DEBUG", default=False))

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = True

SESSION_COOKIE_SECURE = True
                        
CSRF_COOKIE_SECURE = True

SECURE_HSTS_SECONDS = 31536000

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_HSTS_PRELOAD = True
